name = "mblog"
compatibility_date = "2024-01-01"
main = "build/index.js"

[[d1_databases]]
binding = "DB"
database_name = "mblog-db"
database_id = "96782f01-254a-4306-8c93-ec85fcb80ef9"

[build]
command = "npm run build"

[site]
bucket = "./public"

[dev]
port = 8788
