name = "mblog"
compatibility_date = "2024-01-01"
main = "public/_worker.js"

[compatibility_flags]
nodejs_compat = true

[build]
command = "npm run build"

[build.upload]
format = "modules"

[site]
bucket = "./public"

[env.production]
workers_dev = true

pages_build_output_dir = "public"
