name = "mblog"
compatibility_date = "2024-01-01"
main = "public/_worker.js"
pages_build_output_dir = "public"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./public"

[env.production]
workers_dev = true
