name = "mblog"
compatibility_date = "2024-01-01"
main = "public/_worker.js"

[build]
command = "npm run build"

[site]
bucket = "./public"

[build.upload]
format = "modules"

[env.production]
workers_dev = true
